=== huhuiyu/huhuiyu.java/huhuiyu.database/src/main/resources/dbtypes.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="types">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="type" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="type">
		<xs:complexType>
			<xs:attribute name="className" type="xs:string" use="required" />
			<xs:attribute name="mapClassName" type="xs:string" use="optional" />
			<xs:attribute name="shortName" type="xs:string" use="optional" />
			<xs:attribute name="pkName" type="xs:string" use="optional" />
			<xs:attribute name="pkShortName" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== huhuiyu/huhuiyu.java/huhuiyu.database/src/main/resources/dbtypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dbtypes.xsd">
	<!-- 基本数据映射 -->
	<type className="java.lang.Boolean" shortName="boolean" />
	<type className="java.lang.Byte" shortName="byte" />
	<type className="java.lang.Short" shortName="short" />
	<type className="java.lang.Integer" shortName="int" />
	<type className="java.lang.Long" shortName="long" />
	<type className="java.lang.Float" shortName="float" />
	<type className="java.lang.Double" shortName="double" />
	<type className="java.lang.String" shortName="String" />
	<type className="[B" mapClassName="byte[]" shortName="byte[]"
		pkName="byte[]" pkShortName="byte[]" />
	<!-- 其它数据映射 -->
	<type className="oracle.sql.TIMESTAMP" mapClassName="java.sql.Timestamp" />
	<type className="oracle.sql.DATE" mapClassName="java.sql.Date" />
	<type className="java.math.BigInteger" mapClassName="java.lang.Long" />

</types>
